### ISSUE TITLE
Can the pre-trained MASS model be directly used in XLM program ?

### ISSUE THREAD

**Issue by KelleyYin** [microsoft/MASS#1]
If I have pre-trained a MASS model, can I load the model and fine-tune on XLM's supervised training ?

**Comment by tobyoup** [comment]
@KelleyYin  Yes, you can directly use MASS pre-trained model for sequence to sequence task (NMT) in XLM.  Just load the pre-trained model and use the training script for XLM.

**Comment by KelleyYin** [comment]
Thanks a lot. I will try.
Can you provide a pre-trained MASS model of en-fr ?

**Comment by tobyoup** [comment]
We are still under the release review process and will soon provide the pre-trained models.

**Comment by StillKeepTry** [comment]
@KelleyYin You can email me and I will share you en-fr models from cloud storages.

**Comment by KelleyYin** [comment]
@StillKeepTry Thanks for your reply. I will send you an email .
