### ISSUE TITLE
Question abut the construction of your CNNDM dataset

### ISSUE THREAD

**Issue by hokkaido** [microsoft/MASS#104]
I tried to reproduce your results on CNNDM. Comparing the results I get with your [binarized dataset](https://modelrelease.blob.core.windows.net/mass/cnndm.tar.gz) with a tokenized and binarized version that I have derived from the raw CNNDM data myself, I get better ROUGE values when fine-tuning and testing with your dataset than with mine. 

With your binarized dataset, the maximum token length of the article / abstracts per split seem to be as follows:
valid src: 511, valid tgt: 139, train src: 511, train tgt: 172, test src: 511, test tgt: 511

It'd be very helpful if you could shed some light on how you arrived at those lengths. Thanks!

**Comment by StillKeepTry** [comment]
for source data (article), we truncate the sequence in subword-level with maximum length as 512. for target data (title), we truncate the sequence in raw-level with maximum length as 120 (refer to 
https://arxiv.org/abs/1704.04368 ), and then transfer it into sub-word level.
