### ISSUE TITLE
How can I use multiple GPU for MASS-unsupNMT?

### ISSUE THREAD

**Issue by lnash94** [microsoft/MASS#107]
In my project I use MASS-unsupNMT. When I run it using one GPU, it displays the error GPU is not enough to run the project. then I tried CUDA_VISIBLE_DEVICE=0,1, but still, it takes only one GPU. can someone please tell me how to use multiple GPUs to the pre-train in unsupNMT?

**Comment by StillKeepTry** [comment]
Do you add `python -m torch.distributed --nproc_per_node 8 `?

**Comment by lnash94** [comment]
Thank you for your support :) Still I was unable to try it using torch.distribution. I reduced  the batch size and  it worked. But when I tried fine tune method, again that error occured. :(
