### ISSUE TITLE
data for summarization

### ISSUE THREAD

**Issue by RebolloM** [microsoft/MASS#111]
This was already asked but it was solved through email here: https://github.com/microsoft/MASS/issues/82

Would you mind posting or sharing what were the steps? I also need to do this for my own data. 

thanks!

**Comment by StillKeepTry** [comment]
Assume the directory for your data is as:
```
data/
├─ train.src
├─ train.tgt
├─ valid.src
├─ valid.tgt
├─ test.src
├─ test.src
├─ dict.src.txt
└─ dict.tgt.txt
```

So the pipeline for data processed is as:
```
python preprocess.py \
  --user-dir mass \
  --task masked_s2s \
  --source-lang src --target-lang tgt \
  --trainpref data/train \
  --validpref data/valid \
  --testpref data/test \
  --destdir processed \
  --srcdict data/dict.src.txt \
  --tgtdict data/dict.tgt.txt 
```
