### ISSUE TITLE
How to create codes_enfr and vocab_enfr for new language pair?

### ISSUE THREAD

**Issue by lnash94** [microsoft/MASS#112]
I'm going to implement a translation using monolingual corpora. In here, I'm trying to use MASS-unsupNMT for my translation implementation. I run the MASS-unsupNMT for English-French dataset. Now  I need to try this for a new language pair. can someone please tell me how to create codes_enfr and vocab_enfr files for new language pair?

**Comment by StillKeepTry** [comment]
You need to use subword-nmt to generate the bpecode for a language pair.
