### ISSUE TITLE
Summarization Inference error

### ISSUE THREAD

**Issue by mayankagrawal93** [microsoft/MASS#117]
Similar issue as to #82 and #111 
I have created my own dataset and run all the required preprocessing steps which includes ` python encode.py ` and `fairseq-preprocess` on my test .story files.
But after these steps, I get a single `test.bin` and `test.idx` file. I dont know how to get src and tgt as separate files as explained in #111  

A step given in Instructions is,

> Rename the shuffix article and title as src and tgt. 

How do I achieve this from the .txt file obtained after `python encode.py` step ?
What am I missing here?

**Comment by StillKeepTry** [comment]
The `shuffix` should be `suffix`. 
Assume the data directory is as:
```
data
|-- train.src
|-- train.tgt
|-- valid.src
|-- valid.tgt
|-- test.src
|-- test.tgt
```
Than running the command to generate data is as:
```
fairseq-preprocess \
    --user-dir mass --task masked_s2s \
    --source-lang src --target-lang tgt \
    --trainpref cnndm/para/train --validpref cnndm/para/valid --testpref cnndm/para/test \
    --destdir cnndm/processed --srcdict dict.txt --tgtdict dict.txt \
    --workers 20
```
