### ISSUE TITLE
Typo in shell script

### ISSUE THREAD

**Issue by deepak1357** [microsoft/MASS#13]
There is a typo in the  `get-data-gigaword.sh`
https://github.com/microsoft/MASS/blob/fee474e17ee1cd9d94df7ff8e31daa0f3446b29d/MASS/get-data-gigaword.sh#L76

It should be:
`TEST_TGT_BPE=$PROC_PATH/test.ar-ti.ti`
It will trough an assertion error while processing the dataset.

**Comment by StillKeepTry** [comment]
@deepak1357 Thank you for pointing out the typo. It has been fixed now.

**Comment by GuyTevet** [comment]
Typo also at line 72 in `get-data-gigaword.sh`

Should be:
```bash
TEST_TGT=$PARA_PATH/test.ar-ti.tr
```

instead of:
```bash
TEST_TGT=$PARA_PATH/test.ar-ti.ar
```
It results both *ti* and *ar* test files to present the titles, may be the cause to the results at #27.
