### ISSUE TITLE
Can I extend zh-en dict to get rid of <UNK> problem in finetuning zh-en sup-NMT ?

### ISSUE THREAD

**Issue by rejae** [microsoft/MASS#130]
Thanks your work and open resources first!
I use your open model zh-en sup-NMT, and infered a few sentences. However, there are some <UNK> words in English sentence, which bring some error in translation. 

 I want to extends dict to solve this problem. 

Can I just finetune your open sup-NMT zh-en model,  by extend the dict (in other words, add some words below your existing dict ) ?

**Comment by StillKeepTry** [comment]
I do not suggest it. but if you really want to do it, you still need to extend the embedding by yourself. It will be troublesome.

**Comment by rejae** [comment]
could you give me some advice to solve this "<unk>" problem? or should  I need to pretrain en-zh sup-NMT model from scratch? 
if so, I wanna know how long to finish this pretraining process roughly.
thanks for your reply. @StillKeepTry
