### ISSUE TITLE
sup-NMT zh-en data processing.

### ISSUE THREAD

**Issue by rejae** [microsoft/MASS#131]
I followed the introduction to build dataset like train.en, train.zh, valid.en, valid.zh and two dict, Then I run ./generate_enzh_data.sh and got the following info:
`| [en] Dictionary: 40000 types
| [en] data//mono//train.en: 300000 sents, 6016269 tokens, 18.8% replaced by <un                                                                                                 k>
| [en] Dictionary: 40000 types
| [en] data//mono//valid.en: 100000 sents, 2007722 tokens, 18.8% replaced by <un                                                                                                 k>
| [zh] Dictionary: 40000 types
| [zh] data//mono//train.zh: 103324 sents, 216782 tokens, 51.5% replaced by <unk                                                                                                 >
| [zh] Dictionary: 40000 types
| [zh] data//mono//valid.zh: 52061 sents, 108678 tokens, 51.6% replaced by <unk>`

My data-zh were not tokenized, and got the 50% unk info.

 I go through the issue about the data preprocessing, and found some people do tokenized for each Chinese charactor. After this I got 6% unk rate for zh-data. 

The en-data's unk rate was about 18.8%, which I think it's probably a little bit high. I split charactor like " . " , " , " and other tokens with words for each sentence, and the unk rate decreased  to 10%.

It seems like before we do  ./generate_enzh_data.sh, we first need to clean our data for en and zh.

Can you tell me the standard procedure about how to clearn en and zh data?

Thank you!

**Comment by 645709712** [comment]
I meet this problem too...Can you tell me how you improve this problem?
