### ISSUE TITLE
How many Gpu needed for Text Summarization of CNNDM fine-tuning ?

### ISSUE THREAD

**Issue by memeda** [microsoft/MASS#134]
Hi, Thanks for the great work!
I found the summarization guid but it lack the info about gpu num.
I searched the issues and found gigaword use `8` gpu? 
So would CNNDM also need 8 gpus with the given script to reproduce the result?

**Comment by nlpyang** [comment]
Hi, I think they used 8 gpus for CNNDM, you can parse the released pt file to see their training arguments.

**Comment by memeda** [comment]
> Hi, I think they used 8 gpus for CNNDM, you can parse the released pt file to see their training arguments.

Great! Thanks
