### ISSUE TITLE
In text summarization

### ISSUE THREAD

**Issue by KawhiZhao** [microsoft/MASS#138]
In the Data section of fine-tuning process, what do you mean by "Rename the shuffix article and title as src and tgt"? I don't find anything related to article and title

**Comment by moutaigua8183** [comment]
> In the Data section of fine-tuning process, what do you mean by "Rename the shuffix article and title as src and tgt"? I don't find anything related to article and title

Do you happen to solve the problem?  I am also confused about the sentence

**Comment by StillKeepTry** [comment]
It is just for an example. For summarization, we usually have paired data. You can consider the input (article in summarization task) as src, and the label (title in summarization) as tgt.
