### ISSUE TITLE
unable to set a proper batch_size in MASS-supNMT pretraining

### ISSUE THREAD

**Issue by vikrant97** [microsoft/MASS#142]
@StillKeepTry  I am trying to pretrain a model using the instructions given in MASS-supNMT directory. But I am getting the following error. I have tried changing the batch_size upto 4096 but then it exceeds the GPU memory limit. Any workaround here to skip the sentences whose size is larger thatn max-token size?

![mass_error](https://user-images.githubusercontent.com/15844694/81960666-ea318f80-962e-11ea-958a-21a12c2e01ab.PNG)

**Comment by vikrant97** [comment]
I manually removed the sentences of certain length greater than 50 and then set the max-token size to  1024 and it worked. But still a workaround in the code itself where the sentences can be ignored would be better. I guess that is included in fairseq's latest version.

**Comment by StillKeepTry** [comment]
Sometimes, we suggest filtering the sentences which length > 250. since the longer sentence will also consume more GPU memory.
