### ISSUE TITLE
is it typo in README (Fine-tuning (CNN / Daily Mail))?

### ISSUE THREAD

**Issue by SoyChae** [microsoft/MASS#144]
Hi, 
first of all, thanks for your hard work.

In Pipeline for Fine-tuning (CNN / Daily Mail) you provided in README, it is written as --task translation_mass and --arch transformer_mass_base in shell file to fine-tune MASS-summarization.

I think --task might be masked_s2s and --arch be  transformer_mass_base.
Could you check this part?

Thanks!

**Comment by StillKeepTry** [comment]
No, `masked_s2s` is for pre-training and `translation_mass` is for fine-tuning.
