### ISSUE TITLE
how to preprocess data and use the finetuned model ?

### ISSUE THREAD

**Issue by 15091444119** [microsoft/MASS#147]
I tried to use the en-ro ft model, but get-data-nmt.sh applies bpe using src_vocab and tgt_vocab, which are not provided. How can I preprocess data and reproduce en-ro results using the ft model ?

**Comment by StillKeepTry** [comment]
You just need to provide `--reload_vocab` and `--reload_codes`, and it will auto-generate src_vocab and tgt_vocab. reload_vocab is at: https://dl.fbaipublicfiles.com/XLM/vocab_enro and reload_codes is at: https://dl.fbaipublicfiles.com/XLM/codes_enro
