### ISSUE TITLE
What is the difference between pretrain-tensor2tensor and MASS?

### ISSUE THREAD

**Issue by guotong1988** [microsoft/MASS#156]
Thank you very much!

**Comment by StillKeepTry** [comment]
What is pretrain-tensor2tensor?

**Comment by guotong1988** [comment]
https://github.com/tensorflow/tensor2tensor

**Comment by guotong1988** [comment]
What is the difference between BART and MASS?

**Comment by bozhenhhu** [comment]
I guess you may be need to read these paper multi-times to unsderstand their differences

**Comment by guotong1988** [comment]
Close because no friendly response.
