### ISSUE TITLE
How is evaluation done?

### ISSUE THREAD

**Issue by deepaknlp** [microsoft/MASS#18]
Hey @StillKeepTry:
I am curious to know how did you get the reference file for evaluation? Did you use the reference file generated by `get-data-<xyz>.sh`?

**Comment by StillKeepTry** [comment]
@deepaknlp What is your meaning? In fact, it will build reference files from `get-data-<xyz>.sh`

**Comment by deepaknlp** [comment]
@StillKeepTry :
As I can see in the generated reference file there are several unknown (`<<unk>>`) words, which will be decarded while evaluation. In this case how the evaluation is correct?
Please let me know if I am mistaken something.

**Comment by StillKeepTry** [comment]
@deepaknlp which task? NMT or gigawords?

**Comment by deepaknlp** [comment]
@StillKeepTry 
gigawords.

**Comment by StillKeepTry** [comment]
Can you use this command to process gigawords dataset in my script: 

`./get-data-gigaword.sh --reload_vocab vocab_en --reload_codes codes_en --replace_ner true --replace_unk true`

This will use a default unk token `unk` to replace all of the unk words like (`<unk>` or `UNK`), and replace ner as a digit (`# => 1`).  But don't forget to recover it at the evaluation (`1 => #`). Besides, i do not have any other special operations in this dataset.

**Comment by deepaknlp** [comment]
Thanks, @StillKeepTry for the detailed explanation. I appreciate it.
I use the same command and generated the reference file. My question is simple if we treat this reference file (with `<unk>`) as a gold standard reference file then the evaluation is not correct. Instead, we should use the original gold standard reference file (without  `<unk>`) for the evaluation.

**Comment by StillKeepTry** [comment]
@deepaknlp Oh, I know your meaning. You means [this version](https://github.com/harvardnlp/sent-summary)  of gigaword dataset may contain too many unk words in the reference files, which causes some mismatch evaluations.

**Comment by deepaknlp** [comment]
Exactly. In this case, how are you getting the numbers reported in the paper?

**Comment by StillKeepTry** [comment]
Currently, I can get `38.73,19.71,35.96` in a 6-6 1024-hidden size model setting. But I am still conducting experiments to evaluate this dataset on different model scales.

**Comment by deepaknlp** [comment]
Good to know @StillKeepTry.
But I think we should use the gold standard reference file to evaluate the performance. I am adapting this model for some other generation task and end up getting very worse score using this strategy (with `<unk>` reference).

**Comment by StillKeepTry** [comment]
@deepaknlp Ok
