### ISSUE TITLE
MASS Fairseq - A request

### ISSUE THREAD

**Issue by sai-prasanna** [microsoft/MASS#21]
Hi, Its exciting that you have added the task to fairseq. One request would be to use fairseq as a library (pip installed), then registering tasks etc instead of forking.

If some inflexibility in fairseq that prevents you from doing that, I will try to help fixing that in fairseq.

**Comment by tobyoup** [comment]
@sai-prasanna  Thanks for you suggestions. We will soon use fairseq as a binary and update the codes. If any concerns, we can first remove this code version, and push it again when the update is done. How about your suggestions?

**Comment by sai-prasanna** [comment]
@tobyoup That's amazing. Thanks, you have saved my team a lot of valuable time by supporting fairseq :D .

**Comment by erip** [comment]
IANAL, but I think the way fairseq is being used currently is not permitted under the BSD license that fairseq maintains. IIUC, MIT-licensed code can appear in BSD code, but not the other way around. As such, I'd almost recommend that MASS be merged into fairseq (proper or forked).

**Comment by tobyoup** [comment]
Currently, we remove the codes. We will soon incorporate fairseq as a library (pip installed). Thanks for your information.

**Comment by tobyoup** [comment]
@sai-prasanna  We have updated the codes, using fairseq with pip install.

**Comment by gvskalyan** [comment]
@tobyoup is there any plan to support unsupervised NMT in MASS on fairseq
