### ISSUE TITLE
File Error When Finetuning Gigawords

### ISSUE THREAD

**Issue by magic282** [microsoft/MASS#22]
Hi,

I downloaded the pre-trained monolingual model for text summarization and preprocessed Gigawords using `get-data-gigaword.sh`.
Then I am trying to finetune it following https://github.com/microsoft/MASS#fine-tuning-2
However, I got a file related error:
```
Traceback (most recent call last):
  File "train.py", line 345, in <module>
    check_data_params(params)
  File "/workspace/MASS/code/MASS/MASS/src/data/loader.py", line 359, in check_data_params
    assert all([all([os.path.isfile(p1) and os.path.isfile(p2) for p1, p2 in paths.values()]) for paths in params.para_dataset.values()])
AssertionError
```
I changed the data path to `./data/processed/giga/` since in the `get-data-gigaword.sh` file the output folder is giga instead of summarization (https://github.com/microsoft/MASS/blob/438be84c5a82b01a63208f4c42073f13a30d88fd/MASS/get-data-gigaword.sh#L46).

Could you please help with this?

Thanks.

**Comment by StillKeepTry** [comment]
What is your command for download gigaword. I use the following command to download gigaword dataset: 
`./get-data-gigaword.sh --replace_ner true --replace_unk true --reload_vocab vocab_en --reload_codes codes_en --gigapath ~/sumdata/`

Besides, you need to specific `--gigapath` as the absolute path of gigaword dataset in  your local server.

**Comment by magic282** [comment]
I download gigawords from https://github.com/harvardnlp/sent-summary
The command I used is the same as you besides --gigapath.
The generated files are:
```
total 1434860
drwxr-xr-x 2      4096 Jun 27 05:14 ./
drwxr-xr-x 5      4096 Jun 27 12:51 ../
-rw-r--r-- 1    535589 Jun 27 05:11 codes
-rw-r--r-- 1    108212 Jun 27 05:12 test.ar-ti.ar
-rw-r--r-- 1   1001743 Jun 27 05:14 test.ar-ti.ar.pth
-rw-r--r-- 1 724156384 Jun 27 05:12 train.ar-ti.ar
-rw-r--r-- 1 327788219 Jun 27 05:14 train.ar-ti.ar.pth
-rw-r--r-- 1 206252733 Jun 27 05:12 train.ar-ti.ti
-rw-r--r-- 1 137469798 Jun 27 05:14 train.ar-ti.ti.pth
-rw-r--r-- 1  36134406 Jun 27 05:12 valid.ar-ti.ar
-rw-r--r-- 1  17236546 Jun 27 05:14 valid.ar-ti.ar.pth
-rw-r--r-- 1  10410000 Jun 27 05:12 valid.ar-ti.ti
-rw-r--r-- 1   7757485 Jun 27 05:14 valid.ar-ti.ti.pth
-rw-r--r-- 1    409972 Jun 27 05:11 vocab.ar-ti
```

**Comment by thatianafernandes** [comment]
I'm also stucked at the same point. Could anyone give any ideas?

**Comment by Colanim** [comment]
Same for me..

**Comment by 520jefferson** [comment]
@StillKeepTry  same for me. i download en de raw corpus ,process with  fastbpe , and finetune mass_ende_1024.pth, then i get the error.

MODEL=../MASS/model_ende/mass_ende_1024.pth

python3 train.py \
  --exp_name unsupMT_ende                              \
  --data_path ../en-de/                                \
  --lgs 'en-fr'                                        \
  --bt_steps 'en-de-en,de-en-de'                       \
  --encoder_only false                                 \
  --emb_dim 1024                                       \
  --n_layers 6                                         \
  --n_heads 8                                          \
  --dropout 0.1                                        \
  --attention_dropout 0.1                              \
  --gelu_activation true                               \
  --tokens_per_batch 2000                              \
  --batch_size 32                                      \
  --bptt 256                                           \
  --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
  --epoch_size 200000                                  \
  --max_epoch 30                                       \
  --eval_bleu true                                     \
  --reload_model "$MODEL,$MODEL"                       \

**Comment by r-vi** [comment]
For anyone else having this issue, putting the /sumdata folder in my home folder i.e. ~/sumdata/ worked for me.

**Comment by amin-nejad** [comment]
It doesn't have to be in your home directory, just as long as you give the absolute path it should work

**Comment by amin-nejad** [comment]
Also have the same problem, providing absolute path to `sumdata` works for preprocessing the dataset but fine-tuning with using the example in the README still gives an AssertionError. It's a slightly different one for me than the one posted above:

```
Traceback (most recent call last):
  File "train.py", line 346, in <module>
    check_model_params(params)
  File "/mimic/data/MASS/MASS/MASS/src/model/__init__.py", line 65, in check_model_params
    assert all([x == '' or os.path.isfile(x) for x in s])
AssertionError
```

**Comment by StillKeepTry** [comment]
@r-vi @amin-nejad @520jefferson @thatianafernandes @magic282  We have released a pre-trained model for summarization task
 (include document-level) on fairseq now. You can use it from [here](https://github.com/microsoft/MASS/tree/master/MASS-summarization/).   In addition, we provide a copy of binarized cnndm data to download.

**Comment by StillKeepTry** [comment]
A binarized data of gigaword dataset can be obtained from [here](https://modelrelease.blob.core.windows.net/mass/gigaword.tar.gz).
