### ISSUE TITLE
run get-data-gigaword.sh failed

### ISSUE THREAD

**Issue by IreneZihuiLi** [microsoft/MASS#24]
Can someone explain how to run the code for summarization?
Run get-data-gigaword.sh give me millions of errors:

`Learning BPE codes...
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//train.ar-ti.ar ...
Read 0 words (0 unique) from text file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//train.ar-ti.ti ...
Read 0 words (0 unique) from text file.
Segmentation fault (core dumped)
BPE learned in /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes
Applying article BPE codes...
Loading codes from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes ...
Read 0 codes from the codes file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//train.ar-ti.ar ...
Read 0 words (0 unique) from text file.
Applying BPE to /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//train.ar-ti.ar ...
Output memory map failed : 22.
Applying title BPE codes...
Loading codes from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes ...
Read 0 codes from the codes file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//train.ar-ti.ti ...
Read 0 words (0 unique) from text file.
Applying BPE to /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//train.ar-ti.ti ...
Output memory map failed : 22.
Extracting vocabulary...
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//train.ar-ti.ar ...
Read 0 words (0 unique) from text file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//train.ar-ti.ti ...
Read 0 words (0 unique) from text file.
Full vocab in: /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//vocab.ar-ti
Loading codes from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes ...
Read 0 codes from the codes file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//valid.ar-ti.ar ...
Read 0 words (0 unique) from text file.
Applying BPE to /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//valid.ar-ti.ar ...
Output memory map failed : 22.
Loading codes from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes ...
Read 0 codes from the codes file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//valid.ar-ti.ti ...
Read 0 words (0 unique) from text file.
Applying BPE to /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//valid.ar-ti.ti ...
Output memory map failed : 22.
Loading codes from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes ...
Read 0 codes from the codes file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//test.ar-ti.ar ...
Read 0 words (0 unique) from text file.
Applying BPE to /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//test.ar-ti.ar ...
Output memory map failed : 22.
Loading codes from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/processed/giga//codes ...
Read 0 codes from the codes file.
Loading vocabulary from /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//test.ar-ti.ar ...
Read 0 words (0 unique) from text file.
Applying BPE to /home/lily/zl379/Projects/ANLP/MASS/MASS/data/para//test.ar-ti.ar ...
Output memory map failed : 22.
INFO - 07/05/19 22:21:53 - 0:00:00 - Read 14 words from the vocabulary file.

Traceback (most recent call last):
  File "/home/lily/zl379/Projects/ANLP/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/data/lily/zl379/Projects/ANLP/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/lily/zl379/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 07/05/19 22:21:54 - 0:00:00 - Read 14 words from the vocabulary file.

Traceback (most recent call last):
  File "/home/lily/zl379/Projects/ANLP/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/data/lily/zl379/Projects/ANLP/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/lily/zl379/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 07/05/19 22:21:54 - 0:00:00 - Read 14 words from the vocabulary file.

Traceback (most recent call last):
  File "/home/lily/zl379/Projects/ANLP/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/data/lily/zl379/Projects/ANLP/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/lily/zl379/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 07/05/19 22:21:55 - 0:00:00 - Read 14 words from the vocabulary file.

Traceback (most recent call last):
  File "/home/lily/zl379/Projects/ANLP/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/data/lily/zl379/Projects/ANLP/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/lily/zl379/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 07/05/19 22:21:55 - 0:00:00 - Read 14 words from the vocabulary file.

Traceback (most recent call last):
  File "/home/lily/zl379/Projects/ANLP/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/data/lily/zl379/Projects/ANLP/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/lily/zl379/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 07/05/19 22:21:56 - 0:00:00 - Read 14 words from the vocabulary file.

Traceback (most recent call last):
  File "/home/lily/zl379/Projects/ANLP/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/data/lily/zl379/Projects/ANLP/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/lily/zl379/anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
`

I downloaded the tools and giga dataset, what else should I do?

**Comment by StillKeepTry** [comment]
@IreneZihuiLi 
First, download gigaword from [this link](https://github.com/harvardnlp/sent-summary).
Extract gigaword, and the directory is like:

```
sumdata/
|--train/
    |-- train.article.txt.gz
    |-- train.title.txt.gz
    |-- valid.article.filter.txt
    |-- valid.title.filter.txt
|-- Giga/
    |-- input.txt
    |-- task1_ref0.txt
|-- DUC2003/
    |-- ....
```

So, we can get binary data by using the following command:
```
gigaword=sumdata # the path of your gigaword dataset 

./get-data-gigaword.sh \
     --replace_ner true \
     --replace_unk true \
     --reload_vocab vocab_en \
     --reload_codes codes_en \
     --gigapath $gigaword
```

I will also upload a binarized data of gigaword dataset in my experiments later.

**Comment by Colanim** [comment]
@StillKeepTry 
Running your command gives me :

> cannot locate BPE codes

When I run :

```
./get-data-gigaword.sh --replace_ner true --replace_unk true --gigapath $gigaword
```

I don't have the `Output memory map failed : 22.` anymore, but it still not working :

> Applying BPE to /home/remondn/workspace/MASS/MASS/data/para//test.ar-ti.ar ...
Modified 17152 words from text file.
INFO - 08/19/19 10:30:31 - 0:00:00 - Read 14 words from the vocabulary file.
>
>Traceback (most recent call last):
  File "/home/remondn/workspace/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/home/remondn/workspace/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/remondn/.venv/sum/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 08/19/19 10:30:31 - 0:00:00 - Read 14 words from the vocabulary file.
>
>Traceback (most recent call last):
  File "/home/remondn/workspace/MASS/MASS/preprocess.py", line 37, in <module>
    data = Dictionary.index_data(txt_path, bin_path, dico)
  File "/home/remondn/workspace/MASS/MASS/src/data/dictionary.py", line 217, in index_data
    assert sentences.min() >= 0
  File "/home/remondn/.venv/sum/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
INFO - 08/19/19 10:30:32 - 0:00:00 - Read 14 words from the vocabulary file.
>
>Saving the data to /home/remondn/workspace/MASS/MASS/data/processed/giga//valid.ar-ti.ar.pth ...
INFO - 08/19/19 10:30:54 - 0:00:22 - 28672504 words (14 unique) in 189651 sentences.
INFO - 08/19/19 10:30:54 - 0:00:22 - 28672504 unknown words (86 unique), covering 100.00% of the data.
INFO - 08/19/19 10:30:54 - 0:00:00 - Read 14 words from the vocabulary file.
>
>Saving the data to /home/remondn/workspace/MASS/MASS/data/processed/giga//valid.ar-ti.ti.pth ...
INFO - 08/19/19 10:31:01 - 0:00:07 - 8440909 words (14 unique) in 189651 sentences.
INFO - 08/19/19 10:31:01 - 0:00:07 - 8440909 unknown words (77 unique), covering 100.00% of the data.
INFO - 08/19/19 10:31:02 - 0:00:00 - Read 14 words from the vocabulary file.
>
>Saving the data to /home/remondn/workspace/MASS/MASS/data/processed/giga//test.ar-ti.ar.pth ...
INFO - 08/19/19 10:31:02 - 0:00:00 - 86613 words (14 unique) in 1951 sentences.
INFO - 08/19/19 10:31:02 - 0:00:00 - 86613 unknown words (68 unique), covering 100.00% of the data.
INFO - 08/19/19 10:31:02 - 0:00:00 - Read 14 words from the vocabulary file.
>
>Saving the data to /home/remondn/workspace/MASS/MASS/data/processed/giga//test.ar-ti.ti.pth ...
INFO - 08/19/19 10:31:02 - 0:00:00 - 86613 words (14 unique) in 1951 sentences.
INFO - 08/19/19 10:31:02 - 0:00:00 - 86613 unknown words (68 unique), covering 100.00% of the data.

**Comment by StillKeepTry** [comment]
@IreneZihuiLi We have released a pre-trained model for summarization task
 (include document-level) on fairseq now. You can use it from [here](https://github.com/microsoft/MASS/tree/master/MASS-summarization/).

**Comment by StillKeepTry** [comment]
A binarized data of gigaword dataset can be obtained from [here](https://modelrelease.blob.core.windows.net/mass/gigaword.tar.gz)
