### ISSUE TITLE
The task of text summary task seems to be missing data ready

### ISSUE THREAD

**Issue by lcl6679292** [microsoft/MASS#26]
It seems that get-data-gigaword.sh only preprocesses the Gigawords data. So how to get the file "/data/processed/en/" used to train the pretrained model? Thank you.

**Comment by StillKeepTry** [comment]
@lcl6679292  Currently, I used all of the English data from WMT Newscrawl, plus the original gigaword data as the training data. But we are still conducting experiments in different en data (e.g., wiki or book corpus) for comparisons. We will summary a better data generation script according to our results in the future.

**Comment by lcl6679292** [comment]
Thank you very much!!By the way, is there only one sentence in the article of the gigaword data?

**Comment by StillKeepTry** [comment]
Yes
