### ISSUE TITLE
 Is the method of get pre-train model's training data the same as the fine-tuning?

### ISSUE THREAD

**Issue by tuanshanyou** [microsoft/MASS#28]
i use the get-data-gigaword.sh to get the fine-tuning data
the method of get pre-trained model's training data is similar to the get-data-gigaword.sh，right?

**Comment by tuanshanyou** [comment]
i use the get-data-gigaword.sh to get the fine-tuning data
the method of get pre-trained model's training data is similar to  the get-data-gigaword.sh，right?

**Comment by StillKeepTry** [comment]
In my current experiments, I use newscrawl English data + gigaword data for pre-training and then use gigaword data at the fine-tuning stage.
