### ISSUE TITLE
[Data Ready] How to get /data/processed/en-fr ?

### ISSUE THREAD

**Issue by hyeseonko** [microsoft/MASS#29]
Hi, thank you for releasing your code of your paper :)
But I encountered some problems when I typed 'python train.py'

# Problem: Data Ready
I typed the commands as follows:

cd MASS
wget https://dl.fbaipublicfiles.com/XLM/codes_enfr
wget https://dl.fbaipublicfiles.com/XLM/vocab_enfr
./get-data-nmt.sh --src en --tgt fr --reload_codes codes_enfr --reload_vocab vocab_enfr

But it says, 
**bash: ./get-data-nmt.sh: Permission denied**

Do you know how to resolve this? and I want to get 'data/processed/en-fr' :)
Thank you so much for reading this issue.

**Comment by StillKeepTry** [comment]
maybe first `chmod u+x ./get-data-nmt.sh`

**Comment by hyeseonko** [comment]
Thank you! I solved the problem :)
