### ISSUE TITLE
How much data is used to train mass-fairseq model ?

### ISSUE THREAD

**Issue by KelleyYin** [microsoft/MASS#31]
Thank you for providing the code of mass-fairseq.
I want to know how much monolingual and bilingual data are used to train the zh-en mass model you provided.

**Comment by StillKeepTry** [comment]
@KelleyYin We used nearly 100M monolingual data for english and chinese data, and 18M bilingual data for zh-en mass model.

**Comment by LibertFan** [comment]
Is the data available? Could you release the .idx data or give a donwload link?
