### ISSUE TITLE
[MEMORY ERROR] RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by hyeseonko** [microsoft/MASS#33]
Hi,

When I try to fine-tune the unsupervised NMT task, I encountered the message as below. Do you know any other way to solve this error rather than reducing the batch size?

RuntimeError: CUDA out of memory. Tried to allocate 367.12 MiB (GPU 0; 10.91 GiB total capacity; 9.64 GiB already allocated; 203.38 MiB free; 249.00 MiB cached)

Thank you for reading this issue :)

**Comment by StillKeepTry** [comment]
@hyeseonko Maybe reduce the batch size or the model size is a proper solution. I will try to add gradient accumulations in the future.

**Comment by hyeseonko** [comment]
Thank you for your kind reply!! :)
