### ISSUE TITLE
Results on CNN/DM dataset ?

### ISSUE THREAD

**Issue by Colanim** [microsoft/MASS#35]
Thanks for the great codebase !

I was wondering if you tried to get the results on CNN / DM dataset (summarization).

If so, can you share it ?

**Comment by tobyoup** [comment]
@Colanim  We will work on CNN/DM dataset and will share you results if ready.

**Comment by StillKeepTry** [comment]
A cnndm fine-tuned model in base setting can be downloaded from [here](https://modelrelease.blob.core.windows.net/mass/cnndm_evaluation.tar.gz).
