### ISSUE TITLE
Use text-summarization model w/o tuning

### ISSUE THREAD

**Issue by Arvedek** [microsoft/MASS#36]
May I know how to used the pretrained model directly without tuning?

**Comment by tobyoup** [comment]
How do you want to directly use the pre-trained model without fine-tuning?

**Comment by Arvedek** [comment]
I don't have gpus on my machine, so I just want to use the model that's already tuned(model and parameters?).

**Comment by bdalal** [comment]
I think you can use the `translate_ensemble.py` or `translate.py` scripts with language set to `ar-ti`.
See this https://github.com/microsoft/MASS/issues/27, although that requires a GPU too unless you modify the script.

**Comment by StillKeepTry** [comment]
A copy of fine-tuned model in cnndm dataset can be downloaded from [here](https://modelrelease.blob.core.windows.net/mass/cnndm_evaluation.tar.gz), and in gigaword dataset can be download from [here](https://modelrelease.blob.core.windows.net/mass/gigaword_evaluation.tar.gz)
