### ISSUE TITLE
EN-only pre-trained model

### ISSUE THREAD

**Issue by feralvam** [microsoft/MASS#39]
Hello,

Thank you for releasing all these models and code. 

I want to fine-tune the EN-only pre-trained model for another monolingual task. I imagine the process is similar to that for the summarization task. As such, I was checking the commands used there and I noticed that the pre-trained model used is named `MODEL=mass_en_1024.pth`. However, the pre-trained model available in the Summarization section is named `mass_summarization_1024.pth`. Should I assume that that's the EN-only pre-trained model that I need to fine-tune?

Thank you.

**Comment by StillKeepTry** [comment]
@feralvam  Yes. you can use this model to fine-tune first. We are still training our model with more data and we will release the better model in the future.

**Comment by feralvam** [comment]
Thanks! And i'll be looking forward to the release of the new model.
