### ISSUE TITLE
how to prepare the data to feed them into the fine-tuned model (Text-Sum)

### ISSUE THREAD

**Issue by GPapangeo** [microsoft/MASS#40]
How can I prepare my data in order to feed them to the fine-tuned model to get the summaries? 
I have transformed them to txt, can I run something similar to that `./get-data-gigaword.sh  --replace_ner true --replace_unk true  --reload_vocab vocab_en --reload_codes codes_en` ?

Thanks!!

**Comment by StillKeepTry** [comment]
@GPapangeo  We have released a pre-trained model (base setting) for summarization task
 (include document-level) on fairseq now. You can use it from [here](https://github.com/microsoft/MASS/tree/master/MASS-summarization/).  

In addition, we provide a copy of binarized cnndm data to download.

**Comment by StillKeepTry** [comment]
A copy of gigaword data can be obtained from [here](https://modelrelease.blob.core.windows.net/mass/gigaword.tar.gz)
