### ISSUE TITLE
Conversational Response Generation

### ISSUE THREAD

**Issue by surbhardwaj** [microsoft/MASS#46]
Hi, when are you going to update the pre-trained model  for Conversational Response Generation.

**Comment by StillKeepTry** [comment]
You can use this [model](https://modelrelease.blob.core.windows.net/mass/mass-base-uncased.tar.gz) to do conversational response generation (in english domain currently). Let question as the source and answer as the target.

**Comment by surbhardwaj** [comment]
Thanks :)
