### ISSUE TITLE
How can I reproduce the en-fr results of unsupervised NMT?

### ISSUE THREAD

**Issue by KelleyYin** [microsoft/MASS#5]
I used the MASS model you provided to fine-tune the en-fr's unsupervised system, but the the results are more than 1BLEU lower than the score reported in the paper.   
My training script is as follow .
```
 3 data=/search/odin/mmyin/XLM/data/processed/en-fr
  4 mass_model=/search/odin/mmyin/MASS/Unsupervised/MASS-EN-FR/mass_enfr_1024.pth
  5 export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
  6 export NGPU=8
  7 
  8 python -m torch.distributed.launch --nproc_per_node=$NGPU train.py\
  9     --exp_name unsupMT_enfr                              \
 10     --exp_id en-fr_1024 \
 11     --data_path $data \
 12     --reload_model $mass_model,$mass_model \
 13     --lgs 'en-fr'                                        \
 14     --bt_steps 'en-fr-en,fr-en-fr'                       \
 15     --encoder_only false                                 \
 16     --emb_dim 1024                                       \
 17     --n_layers 6                                         \
 18     --n_heads 8                                          \
 19     --dropout 0.1                                        \
 20     --attention_dropout 0.1                              \
 21     --gelu_activation true                               \
 22     --tokens_per_batch 1000                              \
 23     --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
 24     --epoch_size 200000                                  \
 25     --max_epoch 50                                      \
 26     --eval_bleu true                                     \
 27     --word_mass 0.5                                      \
 28     --min_len 5                                          \
 29     --stopping_criterion 'valid_en-fr_mt_bleu,10'      \
 30     --validation_metrics 'valid_en-fr_mt_bleu'          \
~                                                                                                                                                             
~                                                                               
```
I used beam search for decoding, and beam-size was set to 10. 
Here are the reproduced scores.
  
UNMT | en-fr | fr-en
---|---|---
MASS|37.5| 34.6| 28.1| 35.0
MASS(our reproduce)|36.16 |33.67

**Comment by StillKeepTry** [comment]
@KelleyYin How many data do you use?

**Comment by KelleyYin** [comment]
> @KelleyYin How many data do you use?

5 M monolingual data

**Comment by StillKeepTry** [comment]
@KelleyYin Maybe use more data to have a try. Here is one of my [training log](https://gist.github.com/StillKeepTry/7c7017b9f2626f90ae1528d190dc48cc). Just 2 epochs can exceed your current results.

**Comment by KelleyYin** [comment]
@StillKeepTry My training los is [here](https://gist.github.com/KelleyYin/1fdef4c9a764bd03036d4cc28e4e10df).
My model was trained for 30 epochs and it took 4 days.
Can you open your training set ?

**Comment by StillKeepTry** [comment]
@KelleyYin Ok. I will upload it on the cloud storage and share it with you. 

Besides, it just used all of news-crawl data. I just remove the sentences which lengths are over 175.

**Comment by StillKeepTry** [comment]
@KelleyYin Here is [en-fr data](https://modelrelease.blob.core.windows.net/mass/en-fr.tar.gz?sv=2018-03-28&ss=bqtf&srt=sco&sp=rwdlacup&se=2019-06-24T17:43:21Z&sig=9kuLhmyYguQo0c355h6IUD%2BWqFmdIMuVAjmPBab30qM%3D&_=1561377906439), i provide the binary files for processed data (as the raw data are more larger), you can download it to replace your training data.

**Comment by KelleyYin** [comment]
@StillKeepTry Very thanks for your reply.

**Comment by StillKeepTry** [comment]
@KelleyYin By the way, would you like to report your result if you finish experiments on my data?

**Comment by KelleyYin** [comment]
@StillKeepTry OK

**Comment by StillKeepTry** [comment]
@KelleyYin By the way, I found you only use 1000 tokens_per_batch, this will also harm some little performance.

**Comment by KelleyYin** [comment]
@StillKeepTry You are right. In XLM , the `1000 tokens_per_batch` is about 1 point BLEU worse than `2000 tokens`. Therefore, I will try to train MASS with 22G's GPUs.

**Comment by KelleyYin** [comment]
@StillKeepTry How much monolingual corpus is your MASS models both en-fr and en-de trained with ?

**Comment by StillKeepTry** [comment]
@KelleyYin I used all of the newscrawl data.

**Comment by tdomhan** [comment]
Possibly silly question: with a setting of `--epoch_size 200000 --max_epoch 100` the training would only see 20,000,000 = 20 million out the 190M + 62M data points. Am I missing something or can I correctly assume the `max_epoch` argument was set higher for the reported results?

**Comment by tobyoup** [comment]
@tdomhan  Yes, you should set the max_epoch higher to cover more data.
