### ISSUE TITLE
Details on preprocessing Cornell Movie Dialog Corpus 

### ISSUE THREAD

**Issue by ngoyal2707** [microsoft/MASS#58]
Great work on MASS and thanks for releasing the code and answering the questions.

I know that "Conversational response generation" section is being worked upon. But I had a really quick question on input data format for Cornell.

1) Are you guys using same preprocessing code as https://github.com/suriyadeepan/datasets/blob/master/seq2seq/cornell_movie_corpus/scripts/prepare_data.py?

2) If the conversation is `[l1, l2, l3, l4, l5]`, are the generated pairs `[(l1, l2), (l3, l4)]` or `[(l1, l2), (l2, l3), (l3, l4), (l4, l5)]`

3) Is the reported `ppl` in `Table 5`, normalized by the num_tokens based on `60k` subword units or standard white-space tokenizer? If it's based on your tokenization, can you please share `#ntokens`, so it's possible to get comparable numbers for different methods?
  
Thanks

**Comment by StillKeepTry** [comment]
It may be similar.
I just directly used [this link](https://github.com/suriyadeepan/datasets/blob/master/seq2seq/cornell_movie_corpus/pull_data.sh) to obtain the data. 
The ppl is reported in subword-level. Usually, it will be better the word-level than 2-5 perplexity.
