### ISSUE TITLE
Will you upload tuned giga word model?

### ISSUE THREAD

**Issue by LiuYixian** [microsoft/MASS#59]

**Comment by LiuYixian** [comment]
I'm interested in your work and want to do some work based on it. You said the tuned model is training 22days ago. Is it finished now and will you update the tuned model? Thank you.
Yixian

**Comment by StillKeepTry** [comment]
Ok, i will prepare it, and update it here later.

**Comment by StillKeepTry** [comment]
@LiuYixian  We have released a pre-trained model (base setting) for summarization task
 (include document-level) on fairseq now. You can use it from [here](https://github.com/microsoft/MASS/tree/master/MASS-summarization/).

**Comment by StillKeepTry** [comment]
@LiuYixian Since gigaword dataset is membership, can you e-mail me to get the Gigaword fine-tuned model or you can provide me your e-mail? I will also send you the processed data. ;)

**Comment by StillKeepTry** [comment]
Gigaword fine-tuned model in base setting can be download from [here](https://modelrelease.blob.core.windows.net/mass/gigaword_evaluation.tar.gz) now.
