### ISSUE TITLE
fast.cc: No such file or directory

### ISSUE THREAD

**Issue by miaodl** [microsoft/MASS#6]
I am trying to run bash file "get-data-nmt.sh".

Compiling fastBPE...
g++: error: fast.cc: No such file or directory
g++: fatal error: no input file

it's like the installation of fastBPE has changed:

from:
g++ -std=c++11 -pthread -O3 fast.cc -o fast

to:
g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast

please take this into consideration.

**Comment by StillKeepTry** [comment]
It has been fixed now.

**Comment by miaodl** [comment]
> It has been fixed now. Thank you

我是中国人，英文辣鸡哈
