### ISSUE TITLE
sentence size keeps exceeding max_tokens limit

### ISSUE THREAD

**Issue by moyid** [microsoft/MASS#69]
Hi, thank you so much for this library. 

I'm running the provided scripts for MASS-supNMT -- I have prepared the data and successfully ran the `generate_enzh_data.sh` script. Now, I'm trying to run the pretraining script, `run_mass_enzh.sh` 

I keep getting an assertion error similar to:
`AssertionError: sentence at index 5198756 of size 2170 exceeds max_tokens limit of 2048!`

I have gone through my mono and para data and deleted long sentences (over 175 tokens), and this error appeared again. Then, I changed the max tokens limit to 4096, and I got the assertion error:

`AssertionError: sentence at index 5198763 of size 5972 exceeds max_tokens limit of 4096!`

The sentence size has increased to exceed the size of the new limit. 

How do I resolve this issue?

**Comment by StillKeepTry** [comment]
@moyid  That is a strange problem. Usually, it is caused that the example exceeds the max_positions (i.e., this sentence really contains 5972 tokens). So, do you do any subword operation after filter sentences over 175 tokens (this will also result in longer sentences).

**Comment by moyid** [comment]
Yes, I did do subword operation after. I guess sentences need to be much shorter still.

**Comment by StillKeepTry** [comment]
So, I think you still need to do a length filter operation on bpe-level data.

**Comment by moyid** [comment]
I have tried cleaning my data and using shorter data, but I'm still getting similar errors. It might potentially be some issues with my dataset. 

What is the data set you trained on for monolingual zhen? I think the repo said it was WMT18 and I am also using that dataset, but there are a few choices for monolingual. Can you point me to the exact data set you used, so that I can try to run the script against that data?

Thank you!

**Comment by moyid** [comment]
This is likely because of some formatting issue in my training data, I switched to a different dataset and didn't run into this issue, although I haven't figured out the exact issue. Closing for now.
