### ISSUE TITLE
How can I make the data for text summarization task?

### ISSUE THREAD

**Issue by deepaknlp** [microsoft/MASS#7]
It seems get-data-nmt.sh is only compatible with NMT. Can you suggest how can I make the data for text summarization task?

**Comment by BinWone** [comment]
+1, the same question.

**Comment by StillKeepTry** [comment]
I will update a script to process summarization data later. By the way, as [gigaword](https://catalog.ldc.upenn.edu/LDC2012T21) dataset is membership, you may need to download it by self. Besides, the Harvard group has provided a download [link](https://github.com/harvardnlp/sent-summary).

**Comment by loretoparisi** [comment]
That's amazing I was waiting a text sum pre-trained model for a long time! Some info about training data here as well: https://github.com/OpenNMT/CTranslate/issues/19

**Comment by magic282** [comment]
It seems that `get-data-gigaword.sh` only preprocesses the Gigawords data. So how to get the file used to train the pretrained model? Thank you.

**Comment by StillKeepTry** [comment]
@deepaknlp @BinWone @loretoparisi @magic282  We have released a pre-trained model for summarization task
 (include document-level) on fairseq now. You can use it from [here](https://github.com/microsoft/MASS/tree/master/MASS-summarization/).
