### ISSUE TITLE
Links in README.md are broken

### ISSUE THREAD

**Issue by alaneckhardt** [microsoft/MASS#72]
Hi,
these link in README don't work:
https://github.com/microsoft/MASS/blob/master/run_mass_enzh.sh
https://github.com/microsoft/MASS/blob/master/ft_mass_enzh.sh
https://github.com/microsoft/MASS/blob/master/translate.sh
https://github.com/microsoft/MASS/blob/master/encode.py

**Comment by StillKeepTry** [comment]
@alaneckhardt fix now.

**Comment by lkdmttg7** [comment]
Its fixed. Give us chance to contribute :P

**Comment by alaneckhardt** [comment]
Great, thanks for quick fix! Closing now.
