### ISSUE TITLE
MASS-SUM mult-gpu question

### ISSUE THREAD

**Issue by jimmyhsia** [microsoft/MASS#75]
Hi ,
I am trying MASS-SUM,And i move those three files to fairseq but it get another error
`Traceback (most recent call last): File "/home/user/.local/bin/fairseq-train", line 11, in <module> load_entry_point('fairseq==0.8.0', 'console_scripts', 'fairseq-train')() File "/home/user/.local/lib/python3.7/site-packages/fairseq_cli/train.py", line 288, in cli_main parser = options.get_training_parser() File "/home/user/.local/lib/python3.7/site-packages/fairseq/options.py", line 22, in get_training_parser parser = get_parser('Trainer', default_task) File "/home/user/.local/lib/python3.7/site-packages/fairseq/options.py", line 164, in get_parser utils.import_user_module(usr_args) File "/home/user/.local/lib/python3.7/site-packages/fairseq/utils.py", line 288, in import_user_module importlib.import_module(module_name) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 677, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 728, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/home/user/MASS/MASS-summarization/mass/__init__.py", line 1, in <module> from . import masked_s2s File "/home/user/MASS/MASS-summarization/mass/masked_s2s.py", line 19, in <module> from .masked_dataset import MaskedLanguagePairDataset ModuleNotFoundError: No module named 'mass.masked_dataset'`

And the files move to fairseq so original directory(mass) is no bert_dictionary.py ,masked_dataset.py ,learned_positional_embedding.py these three files, maybe is the reason
But i keep this three files in original directory(mass) ,it's get ModuleNotFoundError: No module named 'mass' again
Am i do something wrong??
Anyone help thank

**Comment by StillKeepTry** [comment]
For a example: After move `masked_dataset.py` to `fairseq/fairseq/data`, you also need to modify this [line](https://github.com/microsoft/MASS/blob/cda9f59dcbb16dc0cc03f66098390d8b13cd607b/MASS-summarization/mass/masked_s2s.py#L19) `from .masked_dataset import MaskedLanguagePairDataset` as `from fairseq.data import MaskedLanguagePairDataset`. same for other files which have been moved to fairseq.

**Comment by StillKeepTry** [comment]
The first lines in masked_s2s.py can be like: 
```python
import os
import numpy as np

import torch

from collections import OrderedDict
from fairseq import utils
from fairseq.data import (
    data_utils,
    Dictionary,
    TokenBlockDataset,
    MaskedLanguagePairDataset,
    BertDictionary,
)
from fairseq.tasks import FairseqTask, register_task
```

**Comment by jimmyhsia** [comment]
@StillKeepTry  Thank you so much, it's work

**Comment by kosohae** [comment]
Thankssssssssss !!!! it works for me!!
