### ISSUE TITLE
data for summarization

### ISSUE THREAD

**Issue by juliahane** [microsoft/MASS#82]
Hi
I want to run the summarization pipeline, to get the data, I followed the link, 
this is not clear to me how to form the src and trg files, I see only several files with .story suffix, thanks for your help

**Comment by StillKeepTry** [comment]
@juliahane Do you mean this [file](https://modelrelease.blob.core.windows.net/mass/cnndm.tar.gz) ?

**Comment by juliahane** [comment]
Hi
thank you very much for the data, I could use it, but I need to generate these data for my own dataset, I would appreciate assisting me on how should be the format of src/trg data, for me to understand how to create my own data, also I appreciate telling me the procedure to process these data. thanks

**Comment by StillKeepTry** [comment]
Have solve your problem via e-mail.
