### ISSUE TITLE
Binarized data

### ISSUE THREAD

**Issue by juliahane** [microsoft/MASS#87]
I am trying to understand the codes for summarization, second step is binarization, I really appreciate providing me with some explanation, what does binarization mean? thanks

**Comment by juliahane** [comment]
could you also explain why there is only-source option, and why one needs to specify the task name in this stage for dataset processing? 
thanks 

fairseq-preprocess \
    --user-dir mass --only-source --task masked_s2s \
    --trainpref mono/train.txt --validpref mono/valid.txt --testpref mono/test.txt \
    --destdir processed --srcdict dict.txt --workers 60

**Comment by StillKeepTry** [comment]
I have solved your problem via e-mail.
