### ISSUE TITLE
urgent - reproducing table 4 results 

### ISSUE THREAD

**Issue by juliahane** [microsoft/MASS#88]
Hi
I need to reprodcue table 4 baseline result (BERT+LM), I would really appreciate to provide me with the instructions on how to do it, I need this for a deadline, and I would kindly appreciate helping me reproduce your baseline results. So this is before adding the masked language part, and just the baseline result, thanks

**Comment by StillKeepTry** [comment]
This [issue](https://github.com/microsoft/MASS/issues/11) may solve your problem?

**Comment by juliahane** [comment]
Hi
thanks for the response, I need the summarization results not the machine translation one, I greatly appreciate to assist me to reproduce the summarization results of LM+BERT, thanks

**Comment by StillKeepTry** [comment]
I have solved your problem via e-mail.
