### ISSUE TITLE
How to use fairseq-interactive

### ISSUE THREAD

**Issue by huangxianliang** [microsoft/MASS#92]
In my project,i need to use fairseq-interactive,but i don't know the params.

**Comment by StillKeepTry** [comment]
Here is one demo, assume you have a input file in source language, so it can be like:
```
data_dir=processed
user_dir=mass
input_file=src.en
model=checkpoint.pt

fairseq-interactive $data_dir \
        --input $input_file \
	--user-dir $user_dir \
	-s en -t zh \
	--langs en,zh \
	--source-langs en --target-langs zh \
	--mt_steps en-zh \
	--task xmasked_seq2seq \
	--path $model \
```

**Comment by huangxianliang** [comment]
> Here is one demo, assume you have a input file in source language, so it can be like:
> 
> ```
> data_dir=processed
> user_dir=mass
> input_file=src.en
> model=checkpoint.pt
> 
> fairseq-interactive $data_dir \
>         --input $input_file \
> 	--user-dir $user_dir \
> 	-s en -t zh \
> 	--langs en,zh \
> 	--source-langs en --target-langs zh \
> 	--mt_steps en-zh \
> 	--task xmasked_seq2seq \
> 	--path $model \
> ```

@StillKeepTry hi,but,there is a probleam:for key in next(iter(self.datasets.values())).datasets.keys()
StopIteration

**Comment by Hemaybe03259ran** [comment]
> > Here is one demo, assume you have a input file in source language, so it can be like:
> > ```
> > data_dir=processed
> > user_dir=mass
> > input_file=src.en
> > model=checkpoint.pt
> > 
> > fairseq-interactive $data_dir \
> >         --input $input_file \
> > 	--user-dir $user_dir \
> > 	-s en -t zh \
> > 	--langs en,zh \
> > 	--source-langs en --target-langs zh \
> > 	--mt_steps en-zh \
> > 	--task xmasked_seq2seq \
> > 	--path $model \
> > ```
> 
> @StillKeepTry hi,but,there is a probleam:for key in next(iter(self.datasets.values())).datasets.keys()
> StopIteration

me too
