### ISSUE TITLE
masked_block_start

### ISSUE THREAD

**Issue by chen1234yue** [microsoft/MASS#93]
When I try to pretrain mass, one  error occurs. In masked_dataset.py MaskedLanguagePairDataset.__getitem__() method, if masked_len = 1,the masked_block_start = np.random.choice(block[:-int(masked_len)+1 ], 1)[0] will throw exception because -int(masked_len)+1=0. I don't understand why we need to plus one. Could you Please help me ?

**Comment by StillKeepTry** [comment]
It seems like a boundary situation that i ignore, i have fixed it. It can be fixed like:
```python
masked_block_start = np.random.choice(block[:len(block)-int(masked_len)+1 ], 1)[0]
```
And reason why we need to plus one is that if you want to sample a span which length=3 from a length=10 segment (like `a=[0,1,2,3,4,5,6,7,8,9]`), So the start of the span can only be chosen from `a=[0,1,2,3,4,5,6,7]`, i.e., a[:len(a) - len(span) + 1]
